// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_xbqhbtXZUp9DDsSQNmC_Ehzwk4Wy5WE',
    appId: '1:457987491827:web:d0cd6fdea96bb1498f3486',
    messagingSenderId: '457987491827',
    projectId: 'tarea9-de2ed',
    authDomain: 'tarea9-de2ed.firebaseapp.com',
    storageBucket: 'tarea9-de2ed.firebasestorage.app',
    measurementId: 'G-CGFWCYK9BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3XD0jObAMcbv-HJVoQTPt08C_d-naMw',
    appId: '1:457987491827:android:875300172e3861f58f3486',
    messagingSenderId: '457987491827',
    projectId: 'tarea9-de2ed',
    storageBucket: 'tarea9-de2ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvNJ9oh0LhHPgp6PmqKA1M_7zrUZuz0aw',
    appId: '1:457987491827:ios:6f2f404ae93b13d08f3486',
    messagingSenderId: '457987491827',
    projectId: 'tarea9-de2ed',
    storageBucket: 'tarea9-de2ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvNJ9oh0LhHPgp6PmqKA1M_7zrUZuz0aw',
    appId: '1:457987491827:ios:6f2f404ae93b13d08f3486',
    messagingSenderId: '457987491827',
    projectId: 'tarea9-de2ed',
    storageBucket: 'tarea9-de2ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_xbqhbtXZUp9DDsSQNmC_Ehzwk4Wy5WE',
    appId: '1:457987491827:web:b2aa2deee0687cb58f3486',
    messagingSenderId: '457987491827',
    projectId: 'tarea9-de2ed',
    authDomain: 'tarea9-de2ed.firebaseapp.com',
    storageBucket: 'tarea9-de2ed.firebasestorage.app',
    measurementId: 'G-9DJMFTLR0D',
  );
}
